version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: always
    environment:
      - TZ="America/Los_Angeles"
      - DEFAULT_DOMAIN=s.bencuan.me
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=shlink_mariadb
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 9105:8080

  database:
    image: mariadb:10.8
    restart: always
    environment:
      ### TODO ###
      - MARIADB_ROOT_PASSWORD=<MARIADB_ROOT_PASSWORD>
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=<PASSWORD>
    volumes:
      - ./data:/var/lib/mysql
  
  shlink-web-client:
    image: shlinkio/shlink-web-client
    restart: always
    ports:
      - 9200:80