version: "3"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - APP_NAME=TurtleNet
    volumes:
      - /home/turtle/heimdall/config:/config
    ports:
      - 6300:80
      - 6343:443
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.entrypoints=https"
      - "traefik.http.routers.heimdall.rule=Host(`t.bencuan.me`)"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.service=heimdall-svc"
      - "traefik.http.services.heimdall-svc.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true